import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, TextInput, Alert, ActivityIndicator, TouchableOpacity } from 'react-native';
import { Camera, useCameraPermission, useCameraDevice, useCameraFormat, useCodeScanner } from 'react-native-vision-camera';
import { COLORS, FONTS } from '../theme';
import BrandHeader from '../components/BrandHeader';
import Button from '../components/Button';
import { wallet } from '../services/wallet';
import { satsToUsd, btcToUsd } from '../services/price';
import { encodePsbtFrames, decodePsbtFrames, buildCosignRequest } from '../services/btcCosign';
import { tagQr, verifyQr, hasAuthTag } from '../services/qrAuth';
import QRCode from 'react-native-qrcode-svg';

// Scan-to-pay (issue #82). Greenfield camera+sign; reuses wallet.js BTC derivation.
//
// Flow:
//   1. User selects chain: Bitcoin or WayChain (explicit intent, no ambiguity).
//   2. Camera activates with chain locked to selection.
//   3. Scan a QR for the selected chain (BTC: BIP21 bitcoin:addr?amount= or bare address).
//   4. Review target + amount (BTC + USD).
//   5. Derive the user's BTC key from their SAME mnemonic (one wallet, two chains).
//   6. Co-sign model (founder): phone prepares + signs its half, then waits for the
//      COMPUTER companion to approve before broadcast. The companion is issue #83;
//      here we generate the co-sign request payload + id the computer scans/confirms.
//   7. Signing is REAL (ECDSA/secp256k1 via bitcoinjs-lib). Broadcast needs a BTC
//      backend — we surface the signed PSBT, never fake a "sent".
//
// Security: Only QRs with HMAC auth tag (generated by same mnemonic) are accepted.
// Import mode bypasses auth (user is importing their own seed).

function parseQr(data) {
  // Detects chain + target + amount.
  // BTC:  bitcoin:<addr>?amount=  or bare bc1.../1.../3...
  // WAY:  waychain:<addr>?amount= or bare 0x... (64-hex or 20-byte)
  const raw = (data || '').trim();
  try {
    if (raw.toLowerCase().startsWith('bitcoin:')) {
      const rest = raw.slice('bitcoin:'.length);
      const q = rest.indexOf('?');
      const addr = q >= 0 ? rest.slice(0, q) : rest;
      const params = q >= 0 ? new URLSearchParams(rest.slice(q + 1)) : null;
      return { chain: 'btc', addr, amount: params ? (params.get('amount') || '') : '' };
    }
    if (raw.toLowerCase().startsWith('waychain:')) {
      const rest = raw.slice('waychain:'.length);
      const q = rest.indexOf('?');
      const addr = q >= 0 ? rest.slice(0, q) : rest;
      const params = q >= 0 ? new URLSearchParams(rest.slice(q + 1)) : null;
      return { chain: 'way', addr, amount: params ? (params.get('amount') || '') : '' };
    }
    if (/^(bc1|1|3)/.test(raw)) return { chain: 'btc', addr: raw, amount: '' };
    if (/^0x[0-9a-fA-F]{40}([0-9a-fA-F]{24})?$/.test(raw)) return { chain: 'way', addr: raw, amount: '' };
  } catch { /* ignore */ }
  return { chain: '', addr: '', amount: '' };
}

export default function ScanPayScreen({ navigation }) {
  const { hasPermission: cameraPermission, requestPermission: requestCameraPermission } = useCameraPermission();
  const device = useCameraDevice('back');
  const format = useCameraFormat(device, [
    { videoResolution: { width: 1280, height: 720 } },
  ]);
  const codeScanner = useCodeScanner({
    codeTypes: ['qr'],
    onCodeScanned: (codes) => {
      if (scanned || !codes || !codes.length) return;
      onScan({ data: codes[0].value });
    },
  });
  const [scanned, setScanned] = useState(false);
  const [scanMode, setScanMode] = useState('select'); // 'select', 'btc', 'way', 'import'
  const [chain, setChain] = useState('');
  const [target, setTarget] = useState('');
  const [amount, setAmount] = useState('');
  const [btcAddr, setBtcAddr] = useState('');
  const [psbt, setPsbt] = useState('');
  const [signed, setSigned] = useState('');
  const [signedFrames, setSignedFrames] = useState([]);
  const [cosignId, setCosignId] = useState('');
  const [cosignFrames, setCosignFrames] = useState([]);
  const [account, setAccount] = useState(null);
  const [busy, setBusy] = useState('');

  useEffect(() => {
    wallet.loadAccounts().then((a) => setAccount(a && a.length ? a[0] : null));
    // Auto-enter import mode if navigation params specify it
    if (navigation.getState?.().routes?.find(r => r.params?.mode === 'import')) {
      setScanMode('import');
    }
  }, [navigation]);

  const onScan = useCallback((res) => {
    if (scanned) return;
    setScanned(true);
    const raw = res.data || '';
    // Import mode: accept raw recovery phrase or private key without auth check
    if (scanMode === 'import') {
      const onImport = navigation.getState?.().routes?.find(r => r.params?.mode === 'import')?.params?.onImport;
      if (onImport && raw.trim()) {
        onImport(raw.trim());
        navigation.goBack();
        return;
      }
    }
    // ATTACK SURFACE CLOSED: only QRs we generated (HMAC-tagged with the user's
    // own mnemonic) are accepted. Anything else is auto-blocked — no parsing,
    // no signing. This prevents foreign-QR tx-injection / address substitution.
    if (!account || !account.mnemonic) {
      Alert.alert('No wallet', 'Import your recovery phrase before scanning.');
      setScanned(false); return;
    }
    if (!hasAuthTag(raw)) {
      Alert.alert('QR blocked', 'This QR was not generated by your wallet. Refusing to parse (untrusted source).');
      setScanned(false); return;
    }
    const verified = verifyQr(account.mnemonic, raw);
    if (!verified) {
      Alert.alert('QR blocked', 'Authentication tag invalid. This QR is not from your wallet — refused.');
      setScanned(false); return;
    }
    const p = parseQr(verified);
    if (!p.addr) { Alert.alert('Unrecognized QR', 'Scan a bitcoin: or waychain: QR.'); setScanned(false); return; }
    // Validate chain matches user's explicit selection
    if (scanMode === 'btc' && p.chain !== 'btc') {
      Alert.alert('Wrong chain', 'You selected Bitcoin but scanned a WayChain QR. Please scan a Bitcoin QR or go back and select WayChain.');
      setScanned(false); return;
    }
    if (scanMode === 'way' && p.chain !== 'way') {
      Alert.alert('Wrong chain', 'You selected WayChain but scanned a Bitcoin QR. Please scan a WayChain QR or go back and select Bitcoin.');
      setScanned(false); return;
    }
    setChain(p.chain);
    setTarget(p.addr);
    setAmount(p.amount || '');
  }, [scanned, account, scanMode, navigation]);

  const derive = useCallback(() => {
    if (!account || !account.mnemonic) { Alert.alert('No wallet', 'Import your recovery phrase first.'); return null; }
    try {
      const k = wallet.deriveBtcFromMnemonic(account.mnemonic);
      setBtcAddr(k.btcAddress);
      return k;
    } catch (e) { Alert.alert('BTC derive failed', e?.message || 'err'); return null; }
  }, [account]);

  const prepareCosign = () => {
    if (!target) { Alert.alert('Scan first', 'Scan a BTC QR to pay.'); return; }
    if (!account || !account.mnemonic) { Alert.alert('No wallet', 'Import your recovery phrase first.'); return; }
    const id = Math.random().toString(16).slice(2, 10);
    setCosignId(id);
    const req = buildCosignRequest(target, amount || '0', id);
    // Tag each frame so only our companion (same mnemonic) accepts it.
    const frames = encodePsbtFrames(req).map((f) => tagQr(account.mnemonic, f));
    setCosignFrames(frames);
  };

  const signPasted = () => {
    if (!psbt) { Alert.alert('Paste PSBT', 'Paste the PSBT base64 from your BTC backend / companion to sign.'); return; }
    if (!account || !account.mnemonic) { Alert.alert('No wallet', 'Import your recovery phrase first.'); return; }
    const k = derive();
    if (!k) return;
    setBusy('Sign');
    try {
      const signedB64 = wallet.signBtcPsbt(psbt, k.btcPrivHex);
      setSigned(signedB64);
      const frames = encodePsbtFrames(signedB64).map((f) => tagQr(account.mnemonic, f));
      setSignedFrames(frames);
      Alert.alert('Signed', 'PSBT signed by phone. Scan the (authenticated) frames with your computer companion to broadcast.');
    } catch (e) {
      Alert.alert('Sign failed', e?.message || 'err');
    } finally { setBusy(''); }
  };

  const signWaychain = async () => {
    if (!account || !account.privateKey) { Alert.alert('No wallet', 'Import your recovery phrase first.'); return; }
    if (chain !== 'way') { Alert.alert('Not a WayChain QR', 'Scan a waychain: address to sign a WAY tx.'); return; }
    setBusy('Sign');
    try {
      // Build the WayChain tx hash per consensus/serialize.go, sign with Ed25519.
      // from = 64-hex pubkey (wire/balance key), to = scanned target, value = amount (wei).
      const fields = {
        nonce: Date.now() % 100000, // placeholder; real nonce from chain at broadcast
        from: account.publicKey,
        to: target,
        value: amount ? BigInt(Math.round(parseFloat(amount) * 1e18)).toString() : '0',
        gasLimit: 21000,
        lane: 0,
        data: new Uint8Array(0),
        encData: new Uint8Array(0),
      };
      const { hash, sig } = await wallet.signWaychainTx(fields, account.privateKey);
      const payload = JSON.stringify({ chain: 'way', from: account.publicKey, to: target, value: fields.value, hash, sig });
      setSigned(payload);
      // Air-gap: return the signed WAY tx as scannable, AUTHENTICATED frames for the companion.
      const frames = encodePsbtFrames('way:' + payload).map((f) => tagQr(account.mnemonic, f));
      setSignedFrames(frames);
      Alert.alert('Signed (WAY)', 'WayChain tx signed with your Ed25519 key. Scan the frames with your computer companion to broadcast.');
    } catch (e) {
      Alert.alert('Sign failed', e?.message || 'err');
    } finally { setBusy(''); }
  };

  const startScan = (selectedChain) => {
    setScanMode(selectedChain);
    setChain(selectedChain);
    setTarget('');
    setAmount('');
    setScanned(false);
  };

  const resetScan = () => {
    setScanMode('select');
    setChain('');
    setTarget('');
    setAmount('');
    setScanned(false);
  };

  if (!cameraPermission) {
    return (
      <View style={styles.screen}>
        <BrandHeader subtitle="Scan to Pay" />
        <View style={styles.card}><Text style={styles.hint}>Camera permission is required to scan QRs.</Text>
          <Button label="Grant camera" onPress={requestCameraPermission} style={styles.btn} /></View>
      </View>
    );
  }

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.container}>
      <BrandHeader subtitle={scanMode === 'import' ? 'Import Wallet' : (chain === 'way' ? 'Scan to Pay (WAY)' : 'Scan to Pay (BTC)')} />

      {scanMode === 'select' ? (
        <View style={styles.card}>
          <Text style={styles.label}>Select what you want to scan</Text>
          <Text style={styles.hint}>Choose the chain before scanning to prevent errors.</Text>
          <Button label="📷 Scan Bitcoin QR" onPress={() => startScan('btc')} style={styles.btn} />
          <Button label="📷 Scan WayChain QR" onPress={() => startScan('way')} variant="secondary" style={styles.btn} />
        </View>
      ) : !target ? (
        <View style={styles.card}>
          <Text style={styles.label}>Scan a {scanMode === 'btc' ? 'Bitcoin' : 'WayChain'} QR</Text>
          <Button label="← Back" onPress={resetScan} variant="secondary" style={{ marginTop: 0, marginBottom: 10 }} />
          <View style={styles.camWrap}>
            {device && format ? (
              <Camera
                style={styles.cam}
                device={device}
                format={format}
                isActive={!scanned}
                codeScanner={scanned ? undefined : codeScanner}
              />
            ) : (
              <View style={styles.cam}><ActivityIndicator color={COLORS.copper} /></View>
            )}
          </View>
          {scanned && <Button label="Scan again" onPress={() => setScanned(false)} variant="secondary" style={styles.btn} />}
        </View>
      ) : (
        <View style={styles.card}>
          <Text style={styles.label}>Chain: {chain === 'way' ? 'WayChain (WAY)' : 'Bitcoin (BTC)'}</Text>
          <Text style={styles.label}>Pay to</Text>
          <Text style={styles.addr}>{target}</Text>
          <TextInput value={amount} onChangeText={setAmount} placeholder={chain === 'way' ? 'amount (WAY)' : 'amount (BTC)'} placeholderTextColor={COLORS.muted} style={styles.input} keyboardType="decimal-pad" />
          {amount ? <Text style={styles.usd}>≈ ${chain === 'way' ? (parseFloat(amount || '0') * 0.1).toFixed(2) : btcToUsd(amount)}</Text> : null}
          <Text style={styles.hint}>Review before signing. Your {chain === 'way' ? 'WayChain (Ed25519)' : 'BTC (secp256k1)'} key is derived from your SAME recovery phrase (one wallet, two chains).</Text>

          {chain === 'btc' ? (
            <>
              <Button label="Prepare co-sign request" onPress={prepareCosign} disabled={!!busy} style={styles.btn} />
              {cosignFrames.length > 0 ? (
                <View style={styles.framesWrap}>
                  <Text style={styles.label}>Scan with computer companion</Text>
                  {cosignFrames.map((f, i) => (
                    <View key={i} style={styles.frameBox}>
                      <QRCode value={f} size={120} color="#000000" backgroundColor="#FFFFFF" />
                      <Text style={styles.frameIdx}>{i + 1}/{cosignFrames.length}</Text>
                    </View>
                  ))}
                </View>
              ) : null}

              <Text style={[styles.label, { marginTop: 14 }]}>Sign a PSBT (real ECDSA)</Text>
              <TextInput value={psbt} onChangeText={setPsbt} placeholder="paste PSBT base64" placeholderTextColor={COLORS.muted} style={styles.input} autoCapitalize="none" multiline />
              <Button label={busy === 'Sign' ? 'Signing…' : 'Sign PSBT (phone half)'} onPress={signPasted} disabled={!!busy} variant="secondary" style={styles.btn} />
            </>
          ) : (
            <Button label={busy === 'Sign' ? 'Signing…' : 'Sign WAY tx (Ed25519)'} onPress={signWaychain} disabled={!!busy} style={styles.btn} />
          )}

          {signedFrames.length > 0 ? (
            <View style={styles.framesWrap}>
              <Text style={styles.label}>Signed — scan frames with computer to broadcast</Text>
              {signedFrames.map((f, i) => (
                <View key={i} style={styles.frameBox}>
                  <QRCode value={f} size={120} color="#000000" backgroundColor="#FFFFFF" />
                  <Text style={styles.frameIdx}>{i + 1}/{signedFrames.length}</Text>
                </View>
              ))}
            </View>
          ) : null}

          <Text style={styles.note}>Scan-to-pay signs REAL txs — BTC (secp256k1) or WayChain (Ed25519) — from the SAME mnemonic. Broadcast needs a node/API; we surface signed frames, never fake a send. Phone+computer co-sign: phone signs, computer broadcasts (companion = issue #84).</Text>
        </View>
      )}

      <View style={styles.card}>
        <Text style={styles.label}>Your BTC address (receive)</Text>
        <Text style={styles.addr}>{btcAddr || '— derive to show —'}</Text>
        <Button label="Derive BTC key" onPress={derive} style={styles.btn} />
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.parchment },
  container: { flexGrow: 1, padding: 20, paddingBottom: 40 },
  card: { backgroundColor: COLORS.card, borderRadius: 14, padding: 18, marginTop: 14, borderWidth: 1, borderColor: COLORS.border },
  label: { fontFamily: FONTS.medium, fontSize: 13, color: COLORS.muted, textTransform: 'uppercase', letterSpacing: 1, marginTop: 8 },
  addr: { fontFamily: FONTS.mono, fontSize: 11, color: COLORS.copper, marginTop: 6, flexWrap: 'wrap' },
  input: { backgroundColor: COLORS.parchment, color: COLORS.charcoal, padding: 12, borderRadius: 10, marginTop: 8, borderWidth: 1, borderColor: COLORS.border, fontSize: 13 },
  btn: { marginTop: 12 },
  hint: { fontFamily: FONTS.body, fontSize: 12, color: COLORS.muted, marginTop: 6 },
  usd: { fontFamily: FONTS.body, fontSize: 12, color: COLORS.copper, marginTop: 4 },
  camWrap: { marginTop: 10, borderRadius: 12, overflow: 'hidden', height: 280 },
  cam: { flex: 1 },
  cosign: { fontFamily: FONTS.mono, fontSize: 11, color: COLORS.charcoal, marginTop: 8 },
  signed: { fontFamily: FONTS.mono, fontSize: 10, color: COLORS.copper, marginTop: 8 },
  framesWrap: { marginTop: 10 },
  frameBox: { alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 8, padding: 6, marginTop: 8, alignSelf: 'flex-start' },
  frameIdx: { fontFamily: FONTS.mono, fontSize: 10, color: COLORS.muted, marginTop: 2 },
  note: { fontFamily: FONTS.body, fontSize: 11, color: COLORS.muted, marginTop: 12, lineHeight: 16 },
});
